export enum SettingThemeEnum {
    TextBox = 1,
    CheckBox = 2,
    Textarea = 3,
    Editor = 4,
    Images = 5,
    Number = 6,
    Password = 7,
    DanhMucTinTuc = 9,
    Color = 10,
    AlbumAnh = 11,
    BackgroundColor = 13,
    SlideLienKet = 14,
    NhomMenu = 15,
    MultipleDanhMucTin = 16,
    GroupLoaiTin = 18,
    DanhMucSanPham = 19,
    MultipleDanhMucSanPham = 20,
    GroupQuangCao = 21,
    ReplaceColor = 22,
    QuyTrinhDangKy = 24,
}
