export const CatalogConstant = {
    BIEU_MAU: 'SysBieuMau',
    LOAI_HO_SO: 'LoaiHoSos',
    LOAI_LOP: 'LoaiLops',
    NAM_DAO_TAO: 'NamDaoTaos',
    NHOM_KHOA_HOC: 'NhomKhoaHocs',
    KHOA_HOC: 'KhoaHocs',
    CO_SO_DAO_TAO: 'CoSoDaoTaos',
    TRANG_THAI_LOP_HOC: 'LopHocTrangThais',
    TRANG_THAI_HOC_VIEN: 'TrangThaiHocViens',
    BIEU_MAU_DYNAMICS: 'SysBieuMauDynamics',
    XEP_LOAI: 'XepLoai',
    LOAI_CHAM_CONG: 'LoaiChamCongGiaoVien',
    MIEN_GIAM: 'MienGiam',
    QUY_TRINH_DANG_KY: 'QuyTrinhDangKy',
    DAN_TOC: 'DanToc',
    PHONG_BAN: 'PhongBan',
    QUOC_GIA: 'QuocGia',
    DON_VI_HOP_TAC: 'DonViHopTac',
    HOP_DONG_DAO_TAO: 'QuanLyHopDong',
    TAI_KHOAN_TT: 'TaiKhoanNganHangThanhToan',

    TINH_TP: 'TinhTP',
    QUAN_HUYEN: 'QuanHuyen',
    PHUONG_XA: 'PhuongXa',

    PHONG_BAN_QUAN_LY: 'PhongBanQuanLy',
    TON_GIAO: 'TonGiao',
    PHONG_HOC: 'PhongHoc',
    LOAI_PHONG: 'LoaiPhongHoc',
    NGAY_LE: 'NgayLe',
};
