export const COLUMN_KEY = {
    COLUMN_KEY: 'key_col',

    KHOA_HOC: 'dtnh_khoa_hoc',
    NAM_DAO_TAO: 'dtnh_nam_dao_tao',
    NHOM_KHOA_HOC: 'dtnh_nhom_khoa_hoc',
    LOAI_HO_SO: 'dtnh_loai_ho_so',
    XEP_LOAI: 'dtnh_xep_loai',
    CO_SO: 'dtnh_co_so',
    HINH_THUC_THANH_TOAN: 'dtnh_hinh_thuc_thanh_toan',
    KHOAN_THU: 'dtnh_khoan_thu',
    KHOAN_CHI: 'dtnh_khoan_chi',
    BIEU_MAU: 'dtnh_bieu_mau',
    THANG_THAI_LOP_HOC: 'dtnh_trang_thai_lop_hoc',
    TRANG_THAI_HOC_VIEN: 'dtnh_trang_thai_hoc_vien',
    TINH_THANH_PHO: 'dtnh_tinh_thanh_pho',
    QUAN_HUYEN: 'dtnh_quan_huyen',
    PHUONG_XA: 'dtnh_phuong_xa',
    LOAI_CHAM_CONG: 'dtnh_loai_cham_cong',
    QUY_TRINH_DANG_KY: 'dtnh_quy_trinh_dang_ky',
    DAN_TOC: 'dtnh_dan_toc',
    PHONG_BAN: 'dtnh_phong_ban',
    QUOC_GIA: 'dtnh_quoc_gia',
    DON_VI_HOC_TAC: 'dtnh_don_vi_hop_tac',
    HOP_DONG_DAO_TAO: 'dtnh_hop_dong_dao_tao',
    TAI_KHOAN_TT: 'dthn_tai_khoan_tt',
    TIN_TUC: 'dtnh_tin_tuc',
    DANH_MUC: 'dtnh_danh_muc',
    BAI_VIET: 'dtnh_bai_viet',
    TON_GIAO: 'dtnh_ton_giao',
    PHONG_HOC: 'dtnh_phong_hoc',
    NGAY_LE: 'dtnh_ngay_le',
    LOAI_PHONG: 'dtnh_loai_phong',
    LOAI_LOP: 'dtnh_loai_lop',
    DOI_TUONG: 'dtnh_doi_tuong',
    XEP_LICH: 'dtnh_xep_lich',

    LOP_HOC: 'dtnh_lop_hoc',
    LOP_HOC_TIME: 'dtnh_lop_hoc_time',
    LOP_HOC_HOC_VIEN: 'dtnh_lop_hoc_hoc_vien',
    LOP_HOC_DETAIL_HOC_VIEN: 'dtnh_lop_hoc_detail_hoc_vien',
    HOC_VIEN: 'dtnh_hoc_vien',
    DUYET_THONG_TIN: 'dtnh_duyet_thong_tin',
    INFO_MIEN_GIAM_THEO_LOP:'dtnh_info_mien_giam_theo_lop',

    GIANG_VIEN: 'dtnh_giang_vien',
    GIANG_VIEN_ACCOUNT: 'dtnh_giang_vien_account',
    QUAN_LY_CHAM_CONG: 'dtnh_quan_ly_cham_cong',

    HOC_VIEN_HO_SO: 'dtnh_hoc_vien_ho_so',
    HO_SO_DINH_KEM: 'dtnh_ho_so_dinh_kem',
    VAN_BANG_SV: 'dtnh_van_bang_sv',
    THU_HOC_PHI: 'dtnh_thu_hoc_phi',
    CHUNG_CHI: 'dtnh_cap_chung_chi',
    CLASSROOM_SCORE: 'dtnh_diem_tong_ket_khoa_hoc',
    DUYET_HOC_PHI: 'dtnh_duyet_hoc_phi',
    HOAN_THANH_KHOA_HOC: 'dtnh_hoan_thanh_khoa_hoc',
    HUY_VAN_BANG: 'dtnh_huy_van_bang',
    DANH_SACH_CHO_MO_LOP: 'dtnh_ds_cho_mo_lop',

    BA0_CAO_THU: 'dtnh_bao_cao_thu',
    BAO_CAO_THU_CHI_TIET: 'dtnh_bao_ca0_thu_chi_tiet',
    BA0_CAO_CHI: 'dtnh_bao_cao_chi',
    BAO_CAO_CHI_CHI_TIET: 'dtnh_bao_cao_chi_chi_tiet',
    CHUONG_TRINH_MIEN_GIAM: 'dtnh_chuong_trinh_mien_giam',
    HOC_VIEN_TAM_NGUNG: 'dtnh_hoc_vien_tam_ngung',
    HOC_VIEN_CHUA_XEP_LOP: 'dtnh_hoc_vien_chua_xep_lop',
    STUDENT_ACCOUNT: 'dtnh_tai_khoan_hoc_vien',
};
