const DEV = (window as any)['env'];
export const environment = {
    production: false,
    name: 'dev',
    storageKey: 'dtnh-web',
    apiServer: DEV.apiServer,
    authServer: DEV.authServer,
    authServerSSO: DEV.authServerSSO,
    redirectServer: DEV.redirectServer,
    // authServerSinhVien: DEV.authServerSinhVien,
    client_id_hrm: DEV.client_id_hrm,
    client_secret_hrm: DEV.client_secret_hrm,
    client_id: DEV.client_id,
    client_secret: DEV.client_secret,
    client_scope: DEV.client_scope,
    redirectUrl: DEV.redirectUrl,
    titleTaskbar: DEV.titleTaskbar,
    version: DEV.version,
    mediaServer: DEV.mediaServer,
    redirectWhenLogout: DEV.redirectWhenLogout,
    logoUrl: DEV.logoUrl,
    favicon: DEV.favicon,
    // authServerAzure: DEV.authServerAzure,
    // tenant: DEV.tenant,
    // client_id_azure: DEV.client_id_azure,

    urlGioiThieu: DEV.urlGioiThieu,
    urlTaiLieu: DEV.urlTaiLieu,
    thoiGianDay: DEV.thoiGianDay,
    serviceName: DEV.serviceName,
    serviceNameRHM: DEV.serviceNameRHM,
};
