export enum RoleActionEnum {
    READ = 1,
    CREATE = 2,
    UPDATE = 3,
    DELETE = 4,
    OPTIONAL = 5,
}

export const RoleAction = {
    Create: 'Create',
    Update: 'Update',
    Delete: 'Delete',
    ExportKhoaHoc: 'ExportKhoaHocAsync',
    ExportNhomKhoaHoc: 'ExportExcelNhomKhoaHocAsync',
    ExportHocVien: 'ExportHocVien',
    ImportHocVien: 'ImportHocVien',
    DuyetHocVienHoSoAsync: 'DuyetHocVienHoSoAsync',
    SubmitDuyetHocPhiAsync: 'SubmitDuyetHocPhiAsync',
    SendMailDongPhiAsync: 'SendMailDongPhiAsync',
    SendEmailActivateAsync: 'SendEmailActivateAsync',
    ChangePasswordForHocVienAsync: 'ChangePasswordForHocVienAsync',
    ChangeStatusLopHocAsync: 'ChangeStatusLopHocAsync',
    ImportLopHocAsync: 'ImportLopHocAsync',
    ExportExcelLopHocAsync: 'ExportExcelLopHocAsync',
    SettingLopHocColorAsync: 'SettingLopHocColorAsync',
    HuyHocVienAsync: 'HuyHocVienAsync',
    SettingColorTrangThaiHocVienAsync: 'SettingColorTrangThaiHocVienAsync',
    SendEmailLopHocHocVienAsync: 'SendEmailLopHocHocVienAsync',
    ExportDSHocVienTheoLopAsync: 'ExportDSHocVienTheoLopAsync',
    ExportDSThi_DSGocAsync: 'ExportDSThi_DSGocAsync',
    ExportDSTamNgungAsync: 'ExportDSTamNgungAsync',
    ExportExcelBCThuTongHopAsync: 'ExportExcelBCThuTongHopAsync',
    ExportThongKeHocVienChuaXepLopAsync: 'ExportThongKeHocVienChuaXepLopAsync',
    SendEmailHocVienAsync: 'SendEmailHocVienAsync',
    CreateHocVienTamNgungAsync: 'CreateHocVienTamNgungAsync',
    UpdateCapVanBangAsync: 'UpdateCapVanBangAsync',
    SendEmailDSChoMoLopAsync: 'SendEmailDSChoMoLopAsync',
    KhongDuyetChamCongAsync: 'KhongDuyetChamCongAsync',
    DuyetChamCongAsync: 'DuyetChamCongAsync',
    KhaiBaoChamCongAsync: 'KhaiBaoChamCongAsync',
    GiangVienAsync: 'GiangVienAsync',
    DuyetMienGiamAsync: 'DuyetMienGiamAsync',
    DungMienGiamAsync: 'DungMienGiamAsync',
    ThuHocPhiTheoLopAsync: 'ThuHocPhiTheoLopAsync',
    DMSettingColorTrangThaiHocVienAsync: 'DMSettingColorTrangThaiHocVienAsync',
    ThuHocPhiAsync: 'ThuHocPhiAsync',
    NhapDiemThiLaiAsync: 'NhapDiemThiLaiAsync',
    ImportHocVienHopDongAsync: 'ImportHocVienHopDongAsync',
    ChangePasswordGiangVienAsync: 'ChangePasswordGiangVienAsync',
    CapTaiKhoanAsync: 'CapTaiKhoanAsync',
    ImportNhomKhoaHocAsync: 'ImportNhomKhoaHocAsync',
    ImportKhoaHocAsync: 'ImportKhoaHocAsync',
    SyncPhongBan: 'SyncPhongBan',
    ImportHocVienTheoLopAsync: 'ImportHocVienTheoLopAsync',
    DuplicateChuongTrinhHocAsync: 'DuplicateChuongTrinhHocAsync',
    DuplicateNhomKhoaHocAsync: 'DuplicateNhomKhoaHocAsync',
    DuplicateLichHocAsync: 'DuplicateLichHocAsync',
    LockLichHocAsync: 'LockLichHocAsync',
    AddLopHocAsync: 'AddLopHocAsync',
    DuyetThongTinAsync: 'DuyetThongTinAsync',
};
