window.env = {
    authServer: 'https://devauth.ascvn.vn',
    authServerSSO: 'https://gv.ascvn.com.vn',
    // authServerSinhVien: 'https://sinhvien-ctump.epmt.com.vn',
    client_id_hrm: '30234b15ce8f464bb5119794287bbdb8',
    client_secret_hrm: '513fdd24f5514e7eac3f417586339b86',
    mediaServer: 'https://dev.ascvn.vn',
    redirectServer: 'https://devcourse.ascvn.vn',
    isLoginSSO: false,
    apiServer: 'https://gateway.ascvn.vn',
    client_id: 'angularclient_gv',
    client_secret: 'gmmFjA2vrYvwk4MaaEzYaC555KbwpxPc',
    client_scope: 'openid offline_access',
    version: 'v1',
    redirectUrl: '/dashboard',
    logoUrl: './assets/ctump/logo.png',
    favicon: './assets/ctump/favicon.ico',
    titleLogin: 'Chào mừng bạn đến Hệ thống',
    pathLogoLogin: './assets/images/login/logo.png',
    titleTaskbar: 'Công ty tiến bộ Sài Gòn',
    redirectWhenLogout: '/login',
    descriptionDashboard:
        'Hệ thống được xây dựng và tích hợp nhiều module với những chức năng khác nhau nhưng chúng có mối liên hệ tương quan chặt chẽ thống nhất với nhau.',
    // authServerAzure: 'https://login.microsoftonline.com',
    // tenant: 'c3f89c46-d98c-4c27-a8a9-79861911bfb8',
    // client_id_azure: 'f9d977fa-4ec2-4a50-bd6b-db2bfded3389',

    thoiGianDay: 45,
    serviceName: 'COURSE',
    serviceNameRHM: 'COURSE_RHM',
};
